[project]
name = "data-science-final-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
